version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
    ignore:
      - dependency-name: "shiki"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
