---
description: 
globs: 
alwaysApply: true
---
# Alternef Digital Garden Rules

You are an expert in Quartz v4, TypeScript, Markdown, and digital garden knowledge management systems.

## Project Overview

Alternef Digital Garden is a personal knowledge management system built using Quartz v4, designed as an interconnected knowledge ecosystem. It serves as a personal wiki and knowledge sharing platform, hosted on GitHub Pages.

## Technical Stack

- **Framework**: Quartz v4 (Hugo-based static site generator)
- **Language**: TypeScript
- **Content**: Markdown files with YAML frontmatter
- **Styling**: Custom SCSS with Google Fonts
- **Package Manager**: npm (Node.js 20+) and Bun
- **Version Control**: Git
- **Hosting**: GitHub Pages
- **Base URL**: soushi888.github.io/alternef-digital-garden
- **Build Command**: `bun quartz build --serve`
- **Preview Command**: `cd public && python3 -m http.server 8080`

## Project Structure

- **content/**: All markdown content files
  - **knowledge/**: Main knowledge base organized by domains
  - **blog/**: Blog posts
  - **portfolio/**: Portfolio content
- **src/**: Custom TypeScript components and styles
- **quartz/**: Core Quartz framework files (do not modify)
- **public/**: Generated static site output
- **quartz.config.ts**: Main configuration file
- **quartz.layout.ts**: Layout configuration

## Content Structure

The digital garden organizes knowledge across 7 core domains:

1. **Land and Nature Stewardship**: Permaculture, ecology, biodiversity, regenerative agriculture
2. **Built Environment**: Architecture, urban planning, sustainable building, infrastructure
3. **Tools and Technology**: Software, hardware, digital tools, automation, programming
4. **Culture and Education**: Learning, teaching, arts, philosophy, knowledge systems
5. **Health and Wellbeing**: Physical health, mental health, nutrition, fitness, wellness
6. **Finance and Economics**: Money systems, alternative economies, investment, sustainability
7. **Governance and Community**: Decision-making, organization, social structures, collaboration

## Markdown Conventions

### Frontmatter Requirements

- **Required fields**: title, description
- **Optional fields**: subtitle, aliases, tags, related pages
- **Format example**:
  ```yaml
  ---
  title: Clear, descriptive title
  description: Concise summary of the note's content
  subtitle: Optional additional context
  aliases: 
    - alternative names or references
  tags: 
    - single-level, root-level tags
  related pages:
    - "[[Related Page]]"
  ---
  ```

### Tagging System

- Use single-level, root tags only
- Use kebab-case (e.g., `collective-intelligence`)
- Avoid hierarchical tags (❌ `programming/web`)
- Keep tags simple and atomic
- Consistent tagging helps with navigation and discovery

### Linking Conventions

- Use wikilinks: `[[page-name|Display Name]]`
- Ensure consistent, lowercase filenames with hyphens
- Link to related concepts and pages
- When linking to index files, use the full path from the `knowledge` directory:
  `[[knowledge/path/to/section/index|Display Name]]`
- Backlinks are automatically generated by Quartz

### Content Style

- No first-level header (#) if title exists in metadata
- Use ## for main sections
- Use ### for subsections
- Start with a clear, concise overview
- Use bullet points for key information
- Break complex topics into digestible sections
- Maintain a consistent, philosophical tone
- Emphasize interconnectedness of ideas
- Use callouts for important information:
  ```md
  > [!note] Note title
  > This is a note callout
  ```

## Quartz Configuration

- **Theme**: Custom color palette with light and dark modes
  - Light mode: Soft cream and earth tones with sage green accents
  - Dark mode: Deep forest night with moonlit sage accents
- **Typography**: 
  - Headers: Schibsted Grotesk
  - Body: Source Sans Pro
  - Code: IBM Plex Mono
- **Plugins enabled**: 
  - **Transformers**: FrontMatter, CreatedModifiedDate, SyntaxHighlighting, ObsidianFlavoredMarkdown, GitHubFlavoredMarkdown, TableOfContents, CrawlLinks, Description, Latex
  - **Filters**: RemoveDrafts
  - **Emitters**: AliasRedirects, ComponentResources, ContentPage, FolderPage, TagPage, ContentIndex, Assets, Static, NotFoundPage

## Coding Guidelines

1. Follow TypeScript best practices
2. Maintain consistent formatting (2 spaces for indentation)
3. Use descriptive variable and function names
4. Document complex logic with comments
5. Keep components modular and reusable
6. Test changes locally before committing
7. Use Prettier for code formatting (configuration in .prettierrc)

## When Suggesting Changes or Additions

- Respect the existing content structure
- Maintain consistent formatting and styling
- Ensure all links are properly formatted
- Verify that new content aligns with the knowledge domains
- Consider the interconnectedness of knowledge when suggesting links
- Preserve the philosophical and holistic approach to knowledge organization
- Follow the principle of atomic notes (one concept per note)
- Suggest relevant tags and related pages

## Common Issues and Solutions

- **Broken links**: Use the CrawlLinks plugin to identify and fix broken links
- **Missing metadata**: Ensure all pages have required frontmatter
- **Inconsistent styling**: Follow the content style guidelines
- **Build errors**: Check console output for specific error messages
- **Preview issues**: Ensure the preview server is running correctly 